image: ubuntu:18.04
stages: 
  - build
  - lint
  - test
  - deploy
  - post_deploy

build_test:
  stage: build
  script:
    - npm install
    - tsc

format_test:
  stage: lint 
  script:
    - npm install
    - prettier --check  "lib/**/*.ts"
    - prettier --check  "bin/**/*.ts"

unit_test:
  stage: test
  script:
    - npm install
    - npm run test

deploy_stack:
  stage: deploy
  script:
    - npm install
    - cdk synth
    - cdk deploy

newman_tests:
  stage: post_deploy
  script:
    - npm install -g newman
    - newman run test/postman/production_tests.postman_collection.json

