image: ubuntu:18.04
stages: 
  - build
  - lint
  - test
  - deploy

format_test:
  stage: lint 
  script:
    - npm install
    - prettier --check  "lib/**/*.ts"
    - prettier --check  "bin/**/*.ts"

unit_test:
  stage: test
  script:
    - npm install
    - npm run test

# newman_test:
#   stage: test
#   script:
