image: ubuntu:18.04
stages: 
  - test

format_test:
  stage: test 
  script:
    - npm install
    - prettier --check  "lib/**/*.ts"
    - prettier --check  "bin/**/*.ts"

unit_test:
  stage: test
  script:
    - npm install
    - npm run test

# newman_test:
#   stage: test
#   script:
