image: ubuntu:18.04
stages: 
  - build
  - lint
  - test
  - deploy
  - post_deploy

cache:
  paths:
    - node_modules/ 
  
build_test:
  stage: build
  script:
    - npm install
    - tsc
  artifacts:
    paths:
      - build      
      - dist

format_test:
  stage: lint 
  script:
    - prettier --check  "lib/**/*.ts"
    - prettier --check  "bin/**/*.ts"

unit_test:
  stage: test
  script:
    - npm run test

deploy_non_production_stack:
  stage: deploy
  variables:
    ENVIRONMENT: "non-prod"
  except:
    - main
  script:
    - echo $ENVIRONMENT
    - npm install
    - npm run build
    - cdk synth
    - cdk deploy --require-approval never

deploy_production_stack:
  stage: deploy
  variables:
    ENVIRONMENT: "prod"
  only:
    - main
  script:
    - echo $ENVIRONMENT
    - cdk synth
    - cdk deploy --require-approval never

newman_tests_production:
  stage: post_deploy
  variables:
    PRODUCTION_URL: $PRODUCTION_URL
    PRODUCTION_API_KEY: $PRODUCTION_API_KEY
  only:
    - main
  script:
    - newman run test/postman/admin_tests.postman_collection.json --env-var "API_KEY"=$PRODUCTION_API_KEY --env-var "Base_API_URL"=$PRODUCTION_URL
    - newman run test/postman/results_tests.postman_collection.json --env-var "API_KEY"=$PRODUCTION_API_KEY --env-var "Base_API_URL"=$PRODUCTION_URL

newman_tests_non_production:
  stage: post_deploy
  variables:
    NON_PRODUCTION_URL: $NON_PRODUCTION_URL
    NON_PRODUCTION_API_KEY: $NON_PRODUCTION_API_KEY
  except:
    - main
  script:
    - newman run test/postman/admin_tests.postman_collection.json --env-var "API_KEY"=$NON_PRODUCTION_API_KEY --env-var "Base_API_URL"=$NON_PRODUCTION_URL
    - newman run test/postman/results_tests.postman_collection.json --env-var "API_KEY"=$NON_PRODUCTION_API_KEY --env-var "Base_API_URL"=$NON_PRODUCTION_URL
