image: ubuntu:18.04
stages: 
  - build
  - lint
  - test
  - deploy
  - post_deploy
  - deploy_production

cache:
  paths:
    - node_modules/ 
  
build_test:
  stage: build
  script:
    - npm install
    - tsc
  artifacts:
    paths:
      - build

format_test:
  stage: lint 
  script:
    - prettier --check  "lib/**/*.ts"
    - prettier --check  "bin/**/*.ts"

unit_test:
  stage: test
  script:
    - npm run test

deploy_stack:
  stage: deploy
  variables:
    ENVIRONMENT: "non-prod"
  script:
    - echo '$ENVIRONMENT'
    - cdk synth
    - cdk deploy --require-approval never

deploy_production_stack:
  stage: deploy
  variables:
    ENVIRONMENT: "prod"
  only:
    - main
  script:
    - echo '$ENVIRONMENT'
    - cdk synth
    - cdk deploy --require-approval never

newman_tests_production:
  stage: post_deploy
  only:
    - main
  script:
    - newman run test/postman/production_tests.postman_collection.json --environment test/postman/production_environment.postman_environment.json

newman_tests_non_production:
  stage: post_deploy
  except:
    - main
  script:
    - newman run test/postman/production_tests.postman_collection.json --environment test/postman/non_production_environment.postman_environment.json
