image: ubuntu:18.04
stages: 
  - build
  - lint
  - test
  - deploy
  - post_deploy
  - deploy_production

build_test:
  stage: build
  script:
    - npm install
    - tsc

format_test:
  stage: lint 
  script:
    - npm install
    - prettier --check  "lib/**/*.ts"
    - prettier --check  "bin/**/*.ts"

unit_test:
  stage: test
  script:
    - npm install
    - npm run test

deploy_stack:
  stage: deploy
  variables:
    ENVIRONMENT: "test"
  script:
    - echo '$ENVIRONMENT'
    - npm install
    - npm run build
    - cdk synth
    - cdk deploy

newman_tests:
  stage: post_deploy
  script:
    - newman run test/postman/production_tests.postman_collection.json --environment test/postman/production_environment.postman_environment.json

deploy_production_stack:
  stage: deploy
  variables:
    ENVIRONMENT: "production"
  only:
    - main
  script:
    - echo '$ENVIRONMENT'
    - npm install
    - npm run build
    - cdk synth
    - cdk deploy
